### ISSUE TITLE
message error infinite loop 

### ISSUE THREAD

**Issue by ferbs** [ThreeDotsLabs/watermill#184] opened 2020-04-20 19:38 UTC
I'm setting up a non-Go system to pass CQRS commands to Watermill over amqp. In my first attempt trying to reproduce the message structure that Watermill expects, I missed the MessageUUIDHeaderKey header (_watermill_message_uuid) which resulted in an infinite Nack loop. Watermill rejects the message before reaching router middleware or the handler, so there's no opportunity to handle the malformed message (eg, w/ a dead letter queue) or otherwise break the infinite loop. 

`subscriber.go:218: 	level=ERROR msg="Processing message failed, sending nack" amqp_exchange_name=dev_primary amqp_queue_name=tasks.SomeTask err="missing _watermill_message_uuid header" topic=tasks.SomeTask`

I suspect an error encountered during unmarshalling might also result in the same behavior.

**Comment by roblaszczak** [comment] 2020-06-14 17:49
Hi @ferbs, what do you think will be expected behavior? 

For example: if we have the scenario when the message was valid, but there was a bug in `MessageUUIDHeaderKey` we may process newer messages, and in some cases, it may move the system to the invalid state (it applies for the brokers, where messages are ordered :wink:). 

From my point of view, it's safer to keep these messages in the queue. My assumption here is that it should be up to the user to handle that in a proper way because it's hard to find here a solution that may work for all message brokers and companies.

Does it make sense for you? :)

**Comment by ferbs** [comment] 2020-06-14 18:30
> up to the user to handle that in a proper way

It sends a Nack too early for the user to handle the case currently.
Apply the watermill header automatically when not already present? Perhaps with an option to disable/skip. 
Otherwise, it could send the Nack later in the process, perhaps in the form of Watermill middleware that a user might modify or configure.

**Comment by hendratommy** [comment] 2020-08-02 05:26
Any reason to enforce the existence of _watermill_message_uuid? I think this makes working with non watermill (such as apache-camel) harder.
Sure we usually need the messageId and agree which header it should be, but it's not enforced. I think watermill should process the message regardless _watermill_message_uuid exists or not, but when watermill produced an message, it would always tag the message with some messageId header.

**Comment by roblaszczak** [comment] 2020-08-19 10:06
Fixed in https://github.com/ThreeDotsLabs/watermill-amqp/pull/4 :)

**Closed by roblaszczak** 2020-08-19 10:06 UTC
Labels: discussion needed
