### ISSUE TITLE
Retry/Middlewares + CQRS busted?

### ISSUE THREAD

**Issue by smazurov** [ThreeDotsLabs/watermill#176] opened 2020-01-31 01:11 UTC
Hey gang, I am opening this as a quick sanity check, I am using CQRS facade and ran into an interesting issue:

If a handler returns an error (or panics) it will retry that handler until the message is successfully processed. I tried using Retry middleware, but it does not work. The reason being, this line https://github.com/ThreeDotsLabs/watermill/blob/8840d3f3fae33785dc9a2ecdae196b83bdcaf01e/message/router/middleware/retry.go#L94 returns an err (which is the err out of the handler) up the stack, instead of processing it inside of the `retryLoop`

simply changing it to 
```golang
return nil, nil
```
fixes the issue.

Whats odd (but perhaps separate) is that `Recoverer` middleware has no effect on actual panics in CQRS. 

In addition, I observed some weird behavior with backoff, and taking a look at the code I don't see how it accounts for backoff time. 

I am happy to submit a PR to change that line if its wrong, but I am afraid I don't quite understand how messages are handled and it could easily break something somewhere else.

**Comment by m110** [comment] 2020-01-31 08:59
Hey @smazurov.

The exit from `Retry` middleware, when the handler returns no error is this line: https://github.com/ThreeDotsLabs/watermill/blob/8840d3f3fae33785dc9a2ecdae196b83bdcaf01e/message/router/middleware/retry.go#L71

The line you mentioned will return the error after several retries, when `break` happens out of the loop.

The change you proposed would make the middleware return no error after several attempts of retry. This would make you lose the message (because it would be acked). If that's the behaviour you're looking for, take a look at `PoisonQueue` middleware: https://watermill.io/docs/middlewares/#poison

Does that make sense?

**Comment by smazurov** [comment] 2020-01-31 18:57
That makes sense, for my own education, whats the point of retry middleware? I guess the assumption is that one handler could be faulty while another handler can handle that message? Ideally what I'm looking for is errors that I know won't ever be resolved for that message (say extra validation), so I want to just get rid of it. PoisonQueue should work, so thanks for that!

Alternatively, would you be open to accepting a PR that adds an option to drop failed messages?

**Comment by m110** [comment] 2020-01-31 20:40
Retry middleware is meant for temporary issues, like some network error while saving to database or an error from an external service. In most cases the Pub/Sub itself will re-deliver the message as it won’t be acked, but using middleware gives you a bit more control. 

PRs are welcome, of course! 🙂 I’d consider making this a separate middleware, something like `DiscardOnError`. Possibly could also allow users to take some action before, like log the message. Although in most cases you’d probably want to use  PoisonQueue anyway, as it might be hard to distinguish between temporary retryable errors and non-fixable errors. 

Also, there’s a common pattern of using both of them in a chain: first, you try to retry the message for several times, and if that doesn’t work that probably means the issue is with message format or other serious error. So PoisonQueue catches it and stores on a separate topic. This is as simple, as adding both middlewares one after another (PoisonQueue first).

**Comment by roblaszczak** [comment] 2020-03-08 14:13
Hello @smazurov, is everything clear now? 
I'm closing the issue but if it shouldn't please let me know :)

**Closed by roblaszczak** 2020-03-08 14:13 UTC
