### ISSUE TITLE
Passing Context  in CQRS

### ISSUE THREAD

**Issue by jpearll** [ThreeDotsLabs/watermill#206] opened 2020-11-10 11:58 UTC
Hi,

I am trying to pass a context from an Event Handler (following CQRS archetype), to another message handler, but it is not working.

From a Command Handler
```
func (h Handler) Handle(ctx context.Context, c interface{}) error {
   // ...
   ctx = context.WithValue(ctx, Key, MyStruct{Field: "test"})
  return h.eventBus.Publish(ctx, &event.UserCreated{})
}
```

To an Event Handler
```
func (h Handler) Handle(ctx context.Context, c interface{}) error {
   // value here is nil
   value  := ctx.Value(Key)
}
```

What is the way to propagate Context across Command & Event Handlers ?

**Comment by roblaszczak** [comment] 2020-12-30 12:51
Hello @jpearll, you should not use context but message metadata instead. 

Context is not propagated by any Pub/Sub (it could be possible only with Go Channel Pub/Sub, but it's not possible currently, it's connected with this PR and discussion https://github.com/ThreeDotsLabs/watermill/pull/205).

Anyway, it's not possible by design, and message metadata was designed to propagate any data that you don't want to send via payload.

I hope it made it clear and I'm closing the issue. If it's not clear, please let me know :)

**Closed by roblaszczak** 2020-12-30 12:51 UTC
